# Devtools
spring:
  messages:
    basename: messages,errors
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  # MySQL 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source URL
    url: [mysql url]
    # DB username
    username: [user id]
    # DB password
    password: [user password]
  # 시작 시, Spring Banner 여부
  main:
    banner-mode: off

  # 파일 크기 설정
  servlet:
    multipart:
      maxFileSize:
        1GB
      maxRequestSize:
        1GB

mybatis:
  type-aliases-package: hello.login.domain.dto
  mapper-locations: mapper/*.xml

# log 설정
logging:
  level:
    root: INFO

jasypt:
  encryptor:
    bean:
      jasyptStringEncryptor

## jasypt secret key
## user password
cypher:
  key:
    annual